#���в�������
onething.disabilityAllowanceAppId: sx_xtddzx
onething.disabilityAllowanceAppKey: sxydP`juOxtdr!Zp0q6
onething.disabilityAllowanceUrl: https://lxbt.mca.gov.cn:8888/cjrlb_test/api/fczk
#Эͬ������������
#onething.dispatchAppId: 200861_app_16703133694014546
#onething.dispatchTenancyId: 610000000001
#onething.dispatchUrl:  http://61.185.238.218:8043/svcreg


onething.dispatchAppId: 200861_app_20201118153052
onething.dispatchTenancyId: 610000000001
onething.dispatchUrl:  https://zwfwxtzx.shaanxi.gov.cn:8202
#��������
onething.download.url: http://172.18.47.124:8680/WebDiskServerDemo/doc
onething.webDisk.appCode : INSPUR-DZZW-
onething.webDisk.decryptKey : 11111


onething.canlian.url: http://59.218.251.18/gatewayjl/api/1/hqxjqhlb

onething.gatewayUrl: http://59.218.152.131:8087/openapi
onething.gatewayAppId: 78606
onething.gatewaySercret: bmirl8LsxKwwxtle1+5zlndW
onething.gatewayKeyId: 3ly4n2ed950v7kpbqa7gky4s52eeulxr

onething.httpProxyIP: 172.24.4.4
onething.httpPort: 3128




