server:
  port: 4000

spring:
  application:
    name: @artifactId@
  resources:
    static-locations: classpath:/res/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: ${MYSQL-USER:ex_sj_workinfo}
      password: ${MYSQL-PWD:123456}
      url: jdbc:oracle:thin:@172.18.10.205:1521/zwfwptgov1
#      username:
#      password: 123456
#      url: jdbc:oracle:thin:@127.0.0.1:1521/inms
#      queryDsSql: 'select * from gen_datasource_conf'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: report
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
mybatis-plus:
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  tenant-enable: ture
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
  type-handlers-package:  io.yunho.yunho.common.data.handler
swagger:
  enabled: true
  title: Inspur Swagger API
  license: Powered By inspur
  licenseUrl: https://inspur.com/
  terms-of-service-url: https://inspur.com/
  contact:
    email: wujiang_job@163.com
    url: https://inspur.com
  authorization:
    name: Inspur Jason
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all