/*
 Navicat Premium Data Transfer

 Source Server         : osi
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 127.0.0.1:1521
 Source Schema         : OSI

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 18/07/2023 09:10:28
*/


-- ----------------------------
-- Table structure for API_DATASOURCE_CONFIG
-- ----------------------------
DROP TABLE "OSI"."API_DATASOURCE_CONFIG";
CREATE TABLE "OSI"."API_DATASOURCE_CONFIG" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "NAME" VARCHAR2(200 BYTE),
  "URL" VARCHAR2(255 BYTE),
  "USER_NAME" VARCHAR2(255 BYTE),
  "PASSWORD" VARCHAR2(50 BYTE),
  "CREATE_TIME" DATE DEFAULT sysdate
,
  "MODIFY_TIME" DATE,
  "DEL_FLAG" CHAR(1 BYTE),
  "DRIVER_TYPE" VARCHAR2(255 BYTE) DEFAULT 'mysql'

)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."NAME" IS '数据连接名称';
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."URL" IS '数据库链接路径';
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."USER_NAME" IS '数据库登录名';
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."PASSWORD" IS '数据库链接密码';
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."MODIFY_TIME" IS '修改时间';
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."DEL_FLAG" IS '0正常 1删除';
COMMENT ON COLUMN "OSI"."API_DATASOURCE_CONFIG"."DRIVER_TYPE" IS '驱动类型';
COMMENT ON TABLE "OSI"."API_DATASOURCE_CONFIG" IS '代理数据源管理表';

-- ----------------------------
-- Table structure for API_DATA_COLUMNS_EXCHANG
-- ----------------------------
DROP TABLE "OSI"."API_DATA_COLUMNS_EXCHANG";
CREATE TABLE "OSI"."API_DATA_COLUMNS_EXCHANG" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "TABLE_ID" VARCHAR2(50 BYTE),
  "LOCAL_COLUMNS" VARCHAR2(200 BYTE),
  "BUSINESS_COLUMNS" VARCHAR2(200 BYTE),
  "CREATE_TIME" DATE DEFAULT sysdate
,
  "MODIFY_TIME" DATE,
  "COMMENTS" VARCHAR2(500 BYTE),
  "REMARK" VARCHAR2(100 BYTE),
  "SCRTPT_ID" VARCHAR2(50 BYTE),
  "COLUMNS_TYPE" VARCHAR2(50 BYTE) DEFAULT 'column'

)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."TABLE_ID" IS '绑定表主键';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."LOCAL_COLUMNS" IS '本地表字段名称';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."BUSINESS_COLUMNS" IS '业务库表字段名称';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."MODIFY_TIME" IS '修改时间';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."COMMENTS" IS '描述';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."REMARK" IS '备注';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."SCRTPT_ID" IS '脚本格式化id';
COMMENT ON COLUMN "OSI"."API_DATA_COLUMNS_EXCHANG"."COLUMNS_TYPE" IS 'column 或者 condition';
COMMENT ON TABLE "OSI"."API_DATA_COLUMNS_EXCHANG" IS '库表交换字段信息表';

-- ----------------------------
-- Table structure for API_DATA_TABLE_EXCHANGE
-- ----------------------------
DROP TABLE "OSI"."API_DATA_TABLE_EXCHANGE";
CREATE TABLE "OSI"."API_DATA_TABLE_EXCHANGE" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "LOCAL_TABLE" VARCHAR2(255 BYTE),
  "BUSINESS_TABLE" VARCHAR2(255 BYTE),
  "DATASOURCE_NAME" VARCHAR2(255 BYTE),
  "CREATE_TIME" DATE DEFAULT sysdate
,
  "MODIFY_TIME" DATE,
  "AIM_DATASOURCE_NAME" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."API_DATA_TABLE_EXCHANGE"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."API_DATA_TABLE_EXCHANGE"."LOCAL_TABLE" IS '本地数据库表名称';
COMMENT ON COLUMN "OSI"."API_DATA_TABLE_EXCHANGE"."BUSINESS_TABLE" IS '业务库表名称';
COMMENT ON COLUMN "OSI"."API_DATA_TABLE_EXCHANGE"."DATASOURCE_NAME" IS '数据库配置名称 与配置表关联';
COMMENT ON COLUMN "OSI"."API_DATA_TABLE_EXCHANGE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "OSI"."API_DATA_TABLE_EXCHANGE"."MODIFY_TIME" IS '修改时间';
COMMENT ON COLUMN "OSI"."API_DATA_TABLE_EXCHANGE"."AIM_DATASOURCE_NAME" IS '目标表数据库配置名称';
COMMENT ON TABLE "OSI"."API_DATA_TABLE_EXCHANGE" IS '库表交换绑定关系表';

-- ----------------------------
-- Table structure for API_INPUT_INFO
-- ----------------------------
DROP TABLE "OSI"."API_INPUT_INFO";
CREATE TABLE "OSI"."API_INPUT_INFO" (
  "ID" VARCHAR2(32 BYTE) NOT NULL,
  "KEY" VARCHAR2(50 BYTE) NOT NULL,
  "PARENT_ID" VARCHAR2(32 BYTE) NOT NULL,
  "API_ID" VARCHAR2(32 BYTE),
  "TYPE" CHAR(1 BYTE),
  "TOKEN_API_ID" VARCHAR2(32 BYTE),
  "IS_TOKEN_CACHE" CHAR(1 BYTE),
  "REMARK" VARCHAR2(255 BYTE),
  "NAME" VARCHAR2(100 BYTE),
  "IS_MUST" CHAR(1 BYTE) DEFAULT '0' ,
  "VALUE" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."KEY" IS '键值';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."PARENT_ID" IS '上层参数ID';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."API_ID" IS '所属接口ID';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."TYPE" IS 'NORMAL/TOKEN/HEADER';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."TOKEN_API_ID" IS '关联的TOKENID';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."IS_TOKEN_CACHE" IS '是否缓存TOKEN，可根据接口设置某规则key';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."REMARK" IS '注释';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."NAME" IS '键值含义';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."IS_MUST" IS '是否必填1是0否';
COMMENT ON COLUMN "OSI"."API_INPUT_INFO"."VALUE" IS '默认值';

-- ----------------------------
-- Table structure for API_OUTPUT_INFO
-- ----------------------------
DROP TABLE "OSI"."API_OUTPUT_INFO";
CREATE TABLE "OSI"."API_OUTPUT_INFO" (
  "ID" VARCHAR2(32 BYTE) NOT NULL,
  "KEY" VARCHAR2(50 BYTE) NOT NULL,
  "NAME" VARCHAR2(100 BYTE),
  "PARENT_ID" VARCHAR2(32 BYTE),
  "REMARK" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."API_OUTPUT_INFO"."KEY" IS '键值';
COMMENT ON COLUMN "OSI"."API_OUTPUT_INFO"."NAME" IS '键值含义';

-- ----------------------------
-- Table structure for API_SCRIPT_INFO
-- ----------------------------
DROP TABLE "OSI"."API_SCRIPT_INFO";
CREATE TABLE "OSI"."API_SCRIPT_INFO" (
  "ID" VARCHAR2(32 BYTE) NOT NULL,
  "RULE_NAME" VARCHAR2(50 BYTE) NOT NULL,
  "RULE_CODE" VARCHAR2(100 BYTE) NOT NULL,
  "RULE_SCRIPT" VARCHAR2(4000 BYTE) NOT NULL,
  "RULE_PARAM" VARCHAR2(4000 BYTE),
  "RULE_TYPE" CHAR(1 BYTE),
  "REGION_CODE" VARCHAR2(12 BYTE),
  "REGION_NAME" VARCHAR2(255 BYTE),
  "ORG_CODE" VARCHAR2(18 BYTE),
  "ORG_NAME" VARCHAR2(255 BYTE),
  "CREATE_TIME" DATE,
  "MODIFY_TIME" DATE,
  "CREATOR" VARCHAR2(50 BYTE),
  "REMARK" VARCHAR2(255 BYTE),
  "STATUS" CHAR(1 BYTE) DEFAULT '1' ,
  "RULE_CLASSIFY" VARCHAR2(20 BYTE) DEFAULT 'other'
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."API_SCRIPT_INFO"."RULE_NAME" IS '脚本名称';
COMMENT ON COLUMN "OSI"."API_SCRIPT_INFO"."RULE_CODE" IS '脚本编码';
COMMENT ON COLUMN "OSI"."API_SCRIPT_INFO"."RULE_SCRIPT" IS '脚本内容';
COMMENT ON COLUMN "OSI"."API_SCRIPT_INFO"."RULE_PARAM" IS '脚本输出参数';
COMMENT ON COLUMN "OSI"."API_SCRIPT_INFO"."RULE_TYPE" IS '1公共脚本，0私有脚本';
COMMENT ON COLUMN "OSI"."API_SCRIPT_INFO"."STATUS" IS '状态 0删除 1正常';
COMMENT ON COLUMN "OSI"."API_SCRIPT_INFO"."RULE_CLASSIFY" IS '脚本分类';

-- ----------------------------
-- Table structure for API_SERVICE_CATALOG
-- ----------------------------
DROP TABLE "OSI"."API_SERVICE_CATALOG";
CREATE TABLE "OSI"."API_SERVICE_CATALOG" (
  "ID" VARCHAR2(32 BYTE) NOT NULL,
  "NAME" VARCHAR2(255 BYTE) NOT NULL,
  "SERVICE_ID" VARCHAR2(36 BYTE),
  "METHOD" VARCHAR2(10 BYTE),
  "URL" VARCHAR2(255 BYTE),
  "VERSION" VARCHAR2(10 BYTE) DEFAULT '1.0'  NOT NULL,
  "TYPE" VARCHAR2(10 BYTE) DEFAULT 'proxy' ,
  "INPUT_ID" VARCHAR2(32 BYTE),
  "OUTPUT_ID" VARCHAR2(32 BYTE),
  "RESULT_TYPE" VARCHAR2(30 BYTE) NOT NULL,
  "REQUEST_TYPE" VARCHAR2(30 BYTE),
  "CREATOR" VARCHAR2(36 BYTE),
  "CREATE_TIME" DATE,
  "MODIFY_TIME" DATE,
  "PUBLISH_TIME" DATE,
  "REMARK" VARCHAR2(255 BYTE),
  "STATUS" CHAR(1 BYTE) DEFAULT '0' ,
  "CALL_TIMES" NUMBER,
  "RETURN_MODE" CHAR(1 BYTE) DEFAULT '1'  NOT NULL,
  "ABLE_APPLIED" CHAR(1 BYTE) DEFAULT '1' ,
  "CHECK_STATE" CHAR(255 BYTE) DEFAULT '9' ,
  "ORIGINAL_URL" VARCHAR2(255 BYTE),
  "REQUEST_MODE" CHAR(1 BYTE) DEFAULT '1'

)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."METHOD" IS 'POST/GET';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."TYPE" IS 'data（数据服务），sql(sql服务)，proxy（代理服务)，callback(回调服务),apply(申请服务)';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."INPUT_ID" IS '入参ID';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."OUTPUT_ID" IS '出参ID';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."RESULT_TYPE" IS 'JSON/XML';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."REQUEST_TYPE" IS 'JSON/XML';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."PUBLISH_TIME" IS '发布时间';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."STATUS" IS '0已保存，1待审核，2已上线，3已下线，4已驳回，9已删除';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."RETURN_MODE" IS '返回方式，1：直接返回源接口数据，2：返回格式化的数据';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."ABLE_APPLIED" IS '共享方式（0：不能被申请，不予共享。1：能被申请，授权码）';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."CHECK_STATE" IS '审核类型 9无 0待审核 1审核通过2审核驳回';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."ORIGINAL_URL" IS '原始接口路径';
COMMENT ON COLUMN "OSI"."API_SERVICE_CATALOG"."REQUEST_MODE" IS '入参方式，1表示无，2表示格式化数据';

-- ----------------------------
-- Table structure for APPROVE_CALL
-- ----------------------------
DROP TABLE "OSI"."APPROVE_CALL";
CREATE TABLE "OSI"."APPROVE_CALL" (
  "CALL_ID" VARCHAR2(32 BYTE) NOT NULL,
  "BSNUM" VARCHAR2(50 BYTE),
  "CALL_STATE" VARCHAR2(2 BYTE) NOT NULL,
  "CALL_PARAMETER" VARCHAR2(32 BYTE),
  "INTERFACE_NAME" VARCHAR2(100 BYTE),
  "CALLED_SYSTEM_CODE" VARCHAR2(32 BYTE),
  "CALLED_SYSTEM_NAME" VARCHAR2(100 BYTE),
  "CALLED_SYSTEM_ADDR" VARCHAR2(200 BYTE),
  "CALL_TIMES" NUMBER,
  "CALL_TIME" DATE,
  "PARAMETER_VALUE" CLOB
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."CALL_ID" IS '主键';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."BSNUM" IS '业务实例号';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."CALL_STATE" IS '调用最终状态,不能为空，0为失败，1为成功';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."CALL_PARAMETER" IS '调用参数';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."INTERFACE_NAME" IS '方法名称';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."CALLED_SYSTEM_CODE" IS '调用系统代码';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."CALLED_SYSTEM_NAME" IS '调用系统名称';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."CALLED_SYSTEM_ADDR" IS '被调用系统地址';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."CALL_TIMES" IS '调用次数';
COMMENT ON COLUMN "OSI"."APPROVE_CALL"."CALL_TIME" IS '调用时间';
COMMENT ON TABLE "OSI"."APPROVE_CALL" IS '接口调用信息';

-- ----------------------------
-- Table structure for APPROVE_CALL_RESULT
-- ----------------------------
DROP TABLE "OSI"."APPROVE_CALL_RESULT";
CREATE TABLE "OSI"."APPROVE_CALL_RESULT" (
  "SEQ_ID" VARCHAR2(32 BYTE) NOT NULL,
  "CALL_ID" VARCHAR2(32 BYTE) NOT NULL,
  "CALL_TIME" DATE NOT NULL,
  "RESULT_VALUE" CLOB,
  "CALL_STATE" VARCHAR2(2 BYTE) NOT NULL,
  "CALLED_SYSTEM_NAME" VARCHAR2(200 BYTE),
  "CALLED_SYSTEM_ADDR" VARCHAR2(200 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."APPROVE_CALL_RESULT"."SEQ_ID" IS '主键';
COMMENT ON COLUMN "OSI"."APPROVE_CALL_RESULT"."CALL_ID" IS '调用ID';
COMMENT ON COLUMN "OSI"."APPROVE_CALL_RESULT"."CALL_TIME" IS '调用时间';
COMMENT ON COLUMN "OSI"."APPROVE_CALL_RESULT"."RESULT_VALUE" IS '调用结果';
COMMENT ON COLUMN "OSI"."APPROVE_CALL_RESULT"."CALL_STATE" IS '调用状态';
COMMENT ON COLUMN "OSI"."APPROVE_CALL_RESULT"."CALLED_SYSTEM_NAME" IS '被调用系统名称';
COMMENT ON COLUMN "OSI"."APPROVE_CALL_RESULT"."CALLED_SYSTEM_ADDR" IS '被调用系统地址';
COMMENT ON TABLE "OSI"."APPROVE_CALL_RESULT" IS '接口调用结果信息';

-- ----------------------------
-- Table structure for WH_CJRZXB_XML_DATA
-- ----------------------------
DROP TABLE "OSI"."WH_CJRZXB_XML_DATA";
CREATE TABLE "OSI"."WH_CJRZXB_XML_DATA" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "NAME" VARCHAR2(255 BYTE),
  "XINGBIE" VARCHAR2(2 BYTE),
  "SHENFENZHENGHAO" VARCHAR2(18 BYTE),
  "CHUSHENGRIQI" VARCHAR2(50 BYTE),
  "HUJIDISUOSHUQUHUA" VARCHAR2(12 BYTE),
  "HUJIDIDIZHI" VARCHAR2(255 BYTE),
  "JUZHUDISUOSHUQUHUA" VARCHAR2(12 BYTE),
  "SHENQINGCANJILEIBIE" VARCHAR2(10 BYTE),
  "JIANHURENXINGMING" VARCHAR2(255 BYTE),
  "YUBENRENGUANXI" VARCHAR2(10 BYTE),
  "JIANHURENSHOUJI" VARCHAR2(20 BYTE),
  "JIANHURENGUDINGDIANHUA" VARCHAR2(20 BYTE),
  "JIESHOUFANGSHI" VARCHAR2(10 BYTE),
  "JIEJIANRENXINGMING" VARCHAR2(255 BYTE),
  "JIEJIANRENGUHUA" VARCHAR2(20 BYTE),
  "JIEJIANRENSHOUJI" VARCHAR2(20 BYTE),
  "JIEJIANRENDIZHI" VARCHAR2(255 BYTE),
  "JUZHUDIDIZHI" VARCHAR2(255 BYTE),
  "BASE_INFO_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."SEQ_ID" IS '主键';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."NAME" IS '姓名';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."XINGBIE" IS '性别';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."SHENFENZHENGHAO" IS '身份证号';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."CHUSHENGRIQI" IS '出生日期';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."HUJIDISUOSHUQUHUA" IS '户籍地所属区划';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."HUJIDIDIZHI" IS '户籍地地址';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JUZHUDISUOSHUQUHUA" IS '居住地所属区划';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."SHENQINGCANJILEIBIE" IS '申请残疾类别';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JIANHURENXINGMING" IS '监护人姓名';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."YUBENRENGUANXI" IS '与本人关系';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JIANHURENSHOUJI" IS '监护人手机';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JIANHURENGUDINGDIANHUA" IS '监护人固定电话';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JIESHOUFANGSHI" IS '接收方式';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JIEJIANRENXINGMING" IS '接件人姓名';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JIEJIANRENGUHUA" IS '接件人固话';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JIEJIANRENSHOUJI" IS '接件人手机';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JIEJIANRENDIZHI" IS '接件人地址';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."JUZHUDIDIZHI" IS '居住地地址';
COMMENT ON COLUMN "OSI"."WH_CJRZXB_XML_DATA"."BASE_INFO_ID" IS '事项编码';
COMMENT ON TABLE "OSI"."WH_CJRZXB_XML_DATA" IS '中残物化表';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESSINFO
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESSINFO";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESSINFO" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "XZQHDM" VARCHAR2(12 BYTE),
  "SXBM" VARCHAR2(50 BYTE) NOT NULL,
  "EXPRESS_TYPE" VARCHAR2(10 BYTE),
  "SBLSH_SHORT" VARCHAR2(50 BYTE),
  "CHANNEL_CODE" VARCHAR2(20 BYTE),
  "IS_USED" VARCHAR2(10 BYTE),
  "CREATE_TIME" DATE,
  "MODIFY_TIME" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."SEQ_ID" IS '主键';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."XZQHDM" IS '行政区划编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."SXBM" IS '事项编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."EXPRESS_TYPE" IS '描述';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."SBLSH_SHORT" IS '办件流水号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."CHANNEL_CODE" IS '渠道';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."IS_USED" IS '是否调用办件查询接口';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESSINFO"."MODIFY_TIME" IS '修改时间';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESS_ACCEPT
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESS_ACCEPT";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESS_ACCEPT" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "SBLSH_SHORT" VARCHAR2(50 BYTE),
  "SXBM" VARCHAR2(50 BYTE),
  "YWSLSJ" DATE,
  "YWLSMC" VARCHAR2(255 BYTE),
  "YWLSZT" CHAR(1 BYTE),
  "YWSLYJ" VARCHAR2(255 BYTE),
  "YWSLQHMC" VARCHAR2(255 BYTE),
  "YWSLQHBM" VARCHAR2(20 BYTE),
  "YWSLBMMC" VARCHAR2(255 BYTE),
  "YWSLBMBM" VARCHAR2(20 BYTE),
  "CREATE_TIME" DATE DEFAULT sysdate

)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."SBLSH_SHORT" IS '申报流水号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."SXBM" IS '事项编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."YWSLSJ" IS '业务受理时间';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."YWLSMC" IS '业务受理名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."YWLSZT" IS '0：不予受理，1：受理';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."YWSLYJ" IS '业务受理意见';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."YWSLQHMC" IS '业务受理区划名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."YWSLQHBM" IS '业务受理区划编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."YWSLBMMC" IS '业务受理部门名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."YWSLBMBM" IS '业务受理部门编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_ACCEPT"."CREATE_TIME" IS '创建时间';
COMMENT ON TABLE "OSI"."XT_APPROVE_BUSINESS_ACCEPT" IS '协同调度受理信息表';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESS_BASE
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESS_BASE";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESS_BASE" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "SBLSH_SHORT" VARCHAR2(50 BYTE),
  "SXBM" VARCHAR2(50 BYTE),
  "SXMC" VARCHAR2(50 BYTE),
  "SXQXBM" VARCHAR2(50 BYTE),
  "XZQHDM" VARCHAR2(12 BYTE),
  "BMMC" VARCHAR2(255 BYTE),
  "BMZZJGDM" VARCHAR2(20 BYTE),
  "YWLY" VARCHAR2(5 BYTE),
  "SBSJ" DATE,
  "SERVICE_OBJ" CHAR(2 BYTE),
  "GR_IDCARDNO" VARCHAR2(20 BYTE),
  "GR_IDENTITYTYPE" VARCHAR2(4 BYTE),
  "GR_LINKPHONE" VARCHAR2(20 BYTE),
  "GR_NAME" VARCHAR2(255 BYTE),
  "QY_ORG_NAME" VARCHAR2(255 BYTE),
  "QY_ORG_CODE" VARCHAR2(20 BYTE),
  "QY_HANDLER_NAME" VARCHAR2(255 BYTE),
  "QY_HANDLER_PHONE" VARCHAR2(20 BYTE),
  "QY_HANDLER_IDTYPE" VARCHAR2(4 BYTE),
  "QY_HANDLER_ID" VARCHAR2(20 BYTE),
  "REMARK" VARCHAR2(255 BYTE),
  "CREATE_TIME" DATE DEFAULT sysdate

)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."SBLSH_SHORT" IS '申办流水号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."SXBM" IS '事项编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."SXMC" IS '事项名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."SXQXBM" IS '事项情形编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."XZQHDM" IS '行政区划代码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."BMMC" IS '部门名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."BMZZJGDM" IS '部门统一社会信用代码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."YWLY" IS '业务来源：01 网上申办
02 大厅受理
07 智能终端
08 手机APP
09 微信';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."SBSJ" IS '申报时间';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."SERVICE_OBJ" IS '0个人事项，1法人事项';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."GR_IDCARDNO" IS '个人证件号码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."GR_IDENTITYTYPE" IS '个人证件类型默认为111';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."GR_LINKPHONE" IS '个人联系电话';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."GR_NAME" IS '个人姓名';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."QY_ORG_NAME" IS '企业名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."QY_ORG_CODE" IS '统一社会信用代码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."QY_HANDLER_NAME" IS '办理人姓名';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."QY_HANDLER_PHONE" IS '办理人联系电话';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."QY_HANDLER_IDTYPE" IS '办理人证件类型';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."QY_HANDLER_ID" IS '办理人证件编号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."REMARK" IS '备注';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_BASE"."CREATE_TIME" IS '创建时间';
COMMENT ON TABLE "OSI"."XT_APPROVE_BUSINESS_BASE" IS '协同调用中心基本数据表';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESS_COURSE
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESS_COURSE";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESS_COURSE" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "CURRENT_NODE_ID" VARCHAR2(50 BYTE),
  "CURRENT_NODE_CODE" VARCHAR2(255 BYTE),
  "ACTIVE" CHAR(1 BYTE),
  "SBLSH_SHORT" VARCHAR2(50 BYTE),
  "CREATE_TIME" DATE,
  "MODIFY_TIME" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_COURSE"."SEQ_ID" IS '过程信息id';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_COURSE"."CURRENT_NODE_ID" IS '流程节点id';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_COURSE"."CURRENT_NODE_CODE" IS '流程节点代码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_COURSE"."ACTIVE" IS '活跃节点1代表活跃，0代表执行完成';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_COURSE"."SBLSH_SHORT" IS '申报流水号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_COURSE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_COURSE"."MODIFY_TIME" IS '修改时间';
COMMENT ON TABLE "OSI"."XT_APPROVE_BUSINESS_COURSE" IS '业务过程信息表';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESS_DONE
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESS_DONE";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESS_DONE" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "SBLSH_SHORT" VARCHAR2(50 BYTE),
  "SXBM" VARCHAR2(50 BYTE),
  "BJBMMC" VARCHAR2(255 BYTE),
  "BJBMBM" VARCHAR2(20 BYTE),
  "SPRXM" VARCHAR2(255 BYTE),
  "SPRDM" VARCHAR2(20 BYTE),
  "BJJGDM" CHAR(1 BYTE),
  "BJJGMS" VARCHAR2(500 BYTE),
  "ZFHTHYY" VARCHAR2(500 BYTE),
  "BJSJ" DATE,
  "BZ" VARCHAR2(500 BYTE),
  "CREATE_TIME" DATE DEFAULT sysdate

)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."SBLSH_SHORT" IS '申报信息流水号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."SXBM" IS '事项编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."BJBMMC" IS '办结部门名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."BJBMBM" IS '办结部门编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."SPRXM" IS '审批人姓名';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."SPRDM" IS '审批人代码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."BJJGDM" IS '办结结果代码0：出证办结
1：退回办结
2：作废办结
3：删除办结
5：补正不来办结
6：准予许可
7：不予许可';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."BJJGMS" IS '办结结果描述';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."ZFHTHYY" IS '作废退回原因 1，2，3，5';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."BJSJ" IS '办结时间';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."BZ" IS '回传表单信息 json字符串';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_DONE"."CREATE_TIME" IS '创建时间';
COMMENT ON TABLE "OSI"."XT_APPROVE_BUSINESS_DONE" IS '业务办结信息表';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESS_EMAIL
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESS_EMAIL";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESS_EMAIL" (
  "SEQ_ID" VARCHAR2(50 BYTE),
  "BASE_INFO_ID" VARCHAR2(50 BYTE),
  "MAIL_TYPE" VARCHAR2(2 BYTE),
  "SEND_MAIL_NAME" VARCHAR2(255 BYTE),
  "SEND_MAIL_PHONE" VARCHAR2(20 BYTE),
  "SEND_MAIL_ADDRESS" VARCHAR2(500 BYTE),
  "SEND_MAIL_PROVINCE" VARCHAR2(20 BYTE),
  "SEND_MAIL_CITY" VARCHAR2(20 BYTE),
  "SEND_MAIL_COUNTY" VARCHAR2(20 BYTE),
  "SEND_MAIL_POST_CODE" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."BASE_INFO_ID" IS '主表对应主键id';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."MAIL_TYPE" IS '0：不邮寄 ，1：邮寄';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."SEND_MAIL_NAME" IS '收件人姓名';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."SEND_MAIL_PHONE" IS '收件人电话号码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."SEND_MAIL_ADDRESS" IS '收件人详细地址';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."SEND_MAIL_PROVINCE" IS '收件人省份名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."SEND_MAIL_CITY" IS '收件人地市名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."SEND_MAIL_COUNTY" IS '收件人区县名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_EMAIL"."SEND_MAIL_POST_CODE" IS '收件人邮编';
COMMENT ON TABLE "OSI"."XT_APPROVE_BUSINESS_EMAIL" IS '申报邮寄信息';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESS_MATERIAL
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESS_MATERIAL";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESS_MATERIAL" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "SBLSH_SHORT" VARCHAR2(50 BYTE),
  "STUFF_SEQ" VARCHAR2(50 BYTE),
  "CLMC" VARCHAR2(255 BYTE),
  "WJLX" CHAR(1 BYTE),
  "CLLX" CHAR(1 BYTE),
  "CLSL" NUMBER,
  "ATTACH_NAME" VARCHAR2(500 BYTE),
  "ATTACH_ID" VARCHAR2(50 BYTE),
  "REMARK" VARCHAR2(50 BYTE),
  "ATTACH_BODY" VARCHAR2(200 BYTE),
  "ATTACH_TYPE" VARCHAR2(20 BYTE),
  "ATTACH_PATH" VARCHAR2(150 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."SBLSH_SHORT" IS '申办流水号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."STUFF_SEQ" IS '事项中控平台提供的事项材料编号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."CLMC" IS '事项中控平台提供的事项材料名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."WJLX" IS '0：纸质，1：电子，2：电子证照';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."CLLX" IS '0：原件，1：复印件，2：电子件';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."CLSL" IS '材料数量';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."ATTACH_NAME" IS '材料附件全称（含后缀）';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."ATTACH_ID" IS '材料附件唯一ID';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."REMARK" IS '备注';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."ATTACH_BODY" IS '附件路径';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."ATTACH_TYPE" IS '附件类型';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_MATERIAL"."ATTACH_PATH" IS '网盘ID或证照唯一标识';
COMMENT ON TABLE "OSI"."XT_APPROVE_BUSINESS_MATERIAL" IS '业务材料信息表';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESS_OUTCOME
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESS_OUTCOME";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESS_OUTCOME" (
  "SEQ_ID" VARCHAR2(50 BYTE),
  "WJLX" CHAR(1 BYTE),
  "ATTACH_NAME" VARCHAR2(255 BYTE),
  "ATTACH_BODY" VARCHAR2(500 BYTE),
  "ATTACH_PATH" VARCHAR2(500 BYTE),
  "SBLSH_SHORT" VARCHAR2(50 BYTE),
  "CREATE_TIME" DATE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_OUTCOME"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_OUTCOME"."WJLX" IS '文件类型0：纸质，1：电子，2：电子证照';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_OUTCOME"."ATTACH_NAME" IS '附件名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_OUTCOME"."ATTACH_BODY" IS '附件路径可下载路径';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_OUTCOME"."ATTACH_PATH" IS '网盘ID或证照唯一标识';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_OUTCOME"."SBLSH_SHORT" IS '申办流水号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_OUTCOME"."CREATE_TIME" IS '创建时间';
COMMENT ON TABLE "OSI"."XT_APPROVE_BUSINESS_OUTCOME" IS '业务信息结果物存量接口';

-- ----------------------------
-- Table structure for XT_APPROVE_BUSINESS_XML_CONFIG
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG";
CREATE TABLE "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG" (
  "SEQ_ID" VARCHAR2(50 BYTE),
  "ITEM_ID" VARCHAR2(50 BYTE),
  "XML_CODE" VARCHAR2(50 BYTE),
  "XML_NAME" VARCHAR2(255 BYTE),
  "REMARK" VARCHAR2(255 BYTE),
  "XML_TYPE" VARCHAR2(255 BYTE),
  "XML_SIZE" NUMBER,
  "TYPE" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG"."SEQ_ID" IS '主键id';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG"."ITEM_ID" IS '事项垂管id';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG"."XML_CODE" IS 'xml中字段编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG"."XML_NAME" IS 'xml中字段含义';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG"."REMARK" IS '备注';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG"."XML_TYPE" IS 'xml中字段类型';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG"."XML_SIZE" IS 'xml中字段大小';
COMMENT ON COLUMN "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG"."TYPE" IS '表属性';
COMMENT ON TABLE "OSI"."XT_APPROVE_BUSINESS_XML_CONFIG" IS '业务表单字段配置进入';

-- ----------------------------
-- Table structure for XT_APPROVE_EXCHANGE
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_EXCHANGE";
CREATE TABLE "OSI"."XT_APPROVE_EXCHANGE" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "BASE_INFO_ID" VARCHAR2(50 BYTE),
  "IS_EXCHANGED" VARCHAR2(4 BYTE),
  "EXCHANGE_RESULT" VARCHAR2(4 BYTE),
  "EXCHANEG_TIMES" VARCHAR2(4 BYTE),
  "CREATE_TIME" DATE DEFAULT sysdate,
  "MODIFY_TIME" DATE,
  "BATCH" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_EXCHANGE"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_EXCHANGE"."BASE_INFO_ID" IS '主表基本信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_EXCHANGE"."IS_EXCHANGED" IS '是否交换 0未处理交换 1处理交换';
COMMENT ON COLUMN "OSI"."XT_APPROVE_EXCHANGE"."EXCHANGE_RESULT" IS '是否交换成功 00为交换成功 ';
COMMENT ON COLUMN "OSI"."XT_APPROVE_EXCHANGE"."EXCHANEG_TIMES" IS '交换次数，不能大于3';
COMMENT ON COLUMN "OSI"."XT_APPROVE_EXCHANGE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "OSI"."XT_APPROVE_EXCHANGE"."MODIFY_TIME" IS '交换完成时间';
COMMENT ON COLUMN "OSI"."XT_APPROVE_EXCHANGE"."BATCH" IS '批次';

-- ----------------------------
-- Table structure for XT_APPROVE_ITEMFLOW_CONFIG
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_ITEMFLOW_CONFIG";
CREATE TABLE "OSI"."XT_APPROVE_ITEMFLOW_CONFIG" (
  "SEQ_ID" VARCHAR2(50 BYTE),
  "SXBM" VARCHAR2(50 BYTE),
  "NODE_NAME" VARCHAR2(255 BYTE),
  "PARENT_ID" VARCHAR2(500 BYTE),
  "NODE_CODE" VARCHAR2(50 BYTE),
  "EXCHANGE_TYPE" CHAR(1 BYTE),
  "CREATE_TIME" DATE DEFAULT sysdate,
  "API_ID" VARCHAR2(50 BYTE),
  "TABLE_ID" VARCHAR2(50 BYTE),
  "CONDITION" VARCHAR2(255 BYTE),
  "CHILD_VALUE" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."SXBM" IS '单事项编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."NODE_NAME" IS '节点名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."PARENT_ID" IS '父级节点';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."NODE_CODE" IS '节点标识符号';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."EXCHANGE_TYPE" IS '0表示接口调用，1表示库表交换';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."API_ID" IS '交换类型为接口调用时，需要绑定接口id';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."TABLE_ID" IS '库表名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."CONDITION" IS '条件关键字';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMFLOW_CONFIG"."CHILD_VALUE" IS '下级条件值';
COMMENT ON TABLE "OSI"."XT_APPROVE_ITEMFLOW_CONFIG" IS '事项办理流程配置';

-- ----------------------------
-- Table structure for XT_APPROVE_ITEMMATERIAL_CONFIG
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_ITEMMATERIAL_CONFIG";
CREATE TABLE "OSI"."XT_APPROVE_ITEMMATERIAL_CONFIG" (
  "SEQ_ID" VARCHAR2(50 BYTE) NOT NULL,
  "ITEM_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMMATERIAL_CONFIG"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEMMATERIAL_CONFIG"."ITEM_ID" IS '事项垂管id';
COMMENT ON TABLE "OSI"."XT_APPROVE_ITEMMATERIAL_CONFIG" IS '材料信息配置表';

-- ----------------------------
-- Table structure for XT_APPROVE_ITEM_CONFIG
-- ----------------------------
DROP TABLE "OSI"."XT_APPROVE_ITEM_CONFIG";
CREATE TABLE "OSI"."XT_APPROVE_ITEM_CONFIG" (
  "SEQ_ID" VARCHAR2(50 BYTE),
  "SXBM" VARCHAR2(50 BYTE),
  "REGION_CODE" VARCHAR2(12 BYTE),
  "ITEM_NAME" VARCHAR2(255 BYTE),
  "REGION_NAME" VARCHAR2(255 BYTE),
  "ITEM_ID" VARCHAR2(50 BYTE),
  "SERVICE_OBJ" CHAR(1 BYTE) DEFAULT '0'

)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEM_CONFIG"."SEQ_ID" IS '主键信息';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEM_CONFIG"."SXBM" IS '事项编码';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEM_CONFIG"."REGION_CODE" IS '行政区划';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEM_CONFIG"."ITEM_NAME" IS '事项名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEM_CONFIG"."REGION_NAME" IS '区划名称';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEM_CONFIG"."ITEM_ID" IS '事项垂管id';
COMMENT ON COLUMN "OSI"."XT_APPROVE_ITEM_CONFIG"."SERVICE_OBJ" IS '0个人1法人';
COMMENT ON TABLE "OSI"."XT_APPROVE_ITEM_CONFIG" IS '事项中控配置信息表';

-- ----------------------------
-- Checks structure for table API_DATASOURCE_CONFIG
-- ----------------------------
ALTER TABLE "OSI"."API_DATASOURCE_CONFIG" ADD CONSTRAINT "SYS_C0010868" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table API_DATA_COLUMNS_EXCHANG
-- ----------------------------
ALTER TABLE "OSI"."API_DATA_COLUMNS_EXCHANG" ADD CONSTRAINT "SYS_C0010870" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table API_DATA_TABLE_EXCHANGE
-- ----------------------------
ALTER TABLE "OSI"."API_DATA_TABLE_EXCHANGE" ADD CONSTRAINT "SYS_C0010869" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table API_INPUT_INFO
-- ----------------------------
ALTER TABLE "OSI"."API_INPUT_INFO" ADD CONSTRAINT "SYS_C0010864" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table API_INPUT_INFO
-- ----------------------------
ALTER TABLE "OSI"."API_INPUT_INFO" ADD CONSTRAINT "SYS_C0010861" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_INPUT_INFO" ADD CONSTRAINT "SYS_C0010862" CHECK ("KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_INPUT_INFO" ADD CONSTRAINT "SYS_C0010863" CHECK ("PARENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table API_OUTPUT_INFO
-- ----------------------------
ALTER TABLE "OSI"."API_OUTPUT_INFO" ADD CONSTRAINT "SYS_C0010866" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table API_OUTPUT_INFO
-- ----------------------------
ALTER TABLE "OSI"."API_OUTPUT_INFO" ADD CONSTRAINT "SYS_C0010865" CHECK ("KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table API_SCRIPT_INFO
-- ----------------------------
ALTER TABLE "OSI"."API_SCRIPT_INFO" ADD CONSTRAINT "SYS_C0010853" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table API_SCRIPT_INFO
-- ----------------------------
ALTER TABLE "OSI"."API_SCRIPT_INFO" ADD CONSTRAINT "SYS_C0010849" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_SCRIPT_INFO" ADD CONSTRAINT "SYS_C0010850" CHECK ("RULE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_SCRIPT_INFO" ADD CONSTRAINT "SYS_C0010851" CHECK ("RULE_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_SCRIPT_INFO" ADD CONSTRAINT "SYS_C0010852" CHECK ("RULE_SCRIPT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table API_SERVICE_CATALOG
-- ----------------------------
ALTER TABLE "OSI"."API_SERVICE_CATALOG" ADD CONSTRAINT "SYS_C0010860" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table API_SERVICE_CATALOG
-- ----------------------------
ALTER TABLE "OSI"."API_SERVICE_CATALOG" ADD CONSTRAINT "SYS_C0010854" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_SERVICE_CATALOG" ADD CONSTRAINT "SYS_C0010855" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_SERVICE_CATALOG" ADD CONSTRAINT "SYS_C0010857" CHECK ("VERSION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_SERVICE_CATALOG" ADD CONSTRAINT "SYS_C0010858" CHECK ("RESULT_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."API_SERVICE_CATALOG" ADD CONSTRAINT "SYS_C0010859" CHECK ("RETURN_MODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table APPROVE_CALL
-- ----------------------------
ALTER TABLE "OSI"."APPROVE_CALL" ADD CONSTRAINT "SYS_C0010838" PRIMARY KEY ("CALL_ID");

-- ----------------------------
-- Checks structure for table APPROVE_CALL
-- ----------------------------
ALTER TABLE "OSI"."APPROVE_CALL" ADD CONSTRAINT "SYS_C0010834" CHECK ("CALL_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL" ADD CONSTRAINT "SYS_C0010835" CHECK ("CALL_STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL" ADD CONSTRAINT "SYS_C0010836" CHECK ("CALL_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL" ADD CONSTRAINT "SYS_C0010837" CHECK ("CALL_STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table APPROVE_CALL_RESULT
-- ----------------------------
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010833" PRIMARY KEY ("SEQ_ID");

-- ----------------------------
-- Checks structure for table APPROVE_CALL_RESULT
-- ----------------------------
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010825" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010826" CHECK ("CALL_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010827" CHECK ("CALL_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010828" CHECK ("CALL_STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010829" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010830" CHECK ("CALL_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010831" CHECK ("CALL_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."APPROVE_CALL_RESULT" ADD CONSTRAINT "SYS_C0010832" CHECK ("CALL_STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table WH_CJRZXB_XML_DATA
-- ----------------------------
ALTER TABLE "OSI"."WH_CJRZXB_XML_DATA" ADD CONSTRAINT "SYS_C0010843" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table XT_APPROVE_BUSINESSINFO
-- ----------------------------
ALTER TABLE "OSI"."XT_APPROVE_BUSINESSINFO" ADD CONSTRAINT "SYS_C0010841" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "OSI"."XT_APPROVE_BUSINESSINFO" ADD CONSTRAINT "SYS_C0010842" CHECK ("SXBM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table XT_APPROVE_BUSINESS_ACCEPT
-- ----------------------------
ALTER TABLE "OSI"."XT_APPROVE_BUSINESS_ACCEPT" ADD CONSTRAINT "SYS_C0010871" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table XT_APPROVE_BUSINESS_BASE
-- ----------------------------
ALTER TABLE "OSI"."XT_APPROVE_BUSINESS_BASE" ADD CONSTRAINT "SYS_C0010844" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table XT_APPROVE_BUSINESS_COURSE
-- ----------------------------
ALTER TABLE "OSI"."XT_APPROVE_BUSINESS_COURSE" ADD CONSTRAINT "SYS_C0010848" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table XT_APPROVE_BUSINESS_DONE
-- ----------------------------
ALTER TABLE "OSI"."XT_APPROVE_BUSINESS_DONE" ADD CONSTRAINT "SYS_C0010867" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table XT_APPROVE_BUSINESS_MATERIAL
-- ----------------------------
ALTER TABLE "OSI"."XT_APPROVE_BUSINESS_MATERIAL" ADD CONSTRAINT "SYS_C0010846" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table XT_APPROVE_EXCHANGE
-- ----------------------------
ALTER TABLE "OSI"."XT_APPROVE_EXCHANGE" ADD CONSTRAINT "SYS_C0010845" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table XT_APPROVE_ITEMMATERIAL_CONFIG
-- ----------------------------
ALTER TABLE "OSI"."XT_APPROVE_ITEMMATERIAL_CONFIG" ADD CONSTRAINT "SYS_C0010847" CHECK ("SEQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
